### ISSUE TITLE
Diskstation

### ISSUE THREAD

**Issue by totocotonio** [gaudes/ioBroker.diashow#52]
Hallo,
es ist mir nicht möglich auf meine Diskstation zuzugreifen wenn der Port nicht der Standartport ist.

**Comment by gaudes** [comment]
Hi,

sorry, ich habe den Adapter gerade umbenannt :-)

Das neue Repo gibts hier:

https://github.com/gaudes/ioBroker.slideshow

Vom Code her sollte es gehen, wenn Du IPAdresse:Port in der Konfig einträgst.

Ist die Synology sicher vom ioBroker aus erreichbar ? Es gibt teilweise Probleme wenn der ioBroker als Docker-Container auf der Synology läuft.

Hattest Du mir auch schon in Discord geschrieben ?

VG Ralf
